### ISSUE TITLE
Bug in 5-loop evaluation of alpha_s

### ISSUE THREAD

**Issue by s-kuberski** [DavidMStraub/rundec-python#14]
Hi,

there seem to be Bugs in version 3.0 of CRunDec that have been fixed in version 3.1. More specifically, it should read `sum[5]` in https://github.com/DavidMStraub/rundec-python/blob/80802333b6dab0ade6104b4a33e962f043ddb30d/CRunDec3/CRunDec.cpp#L288 and https://github.com/DavidMStraub/rundec-python/blob/80802333b6dab0ade6104b4a33e962f043ddb30d/CRunDec3/CRunDec.cpp#L308 . With the current version, the fuctions `AlphasLam` and `fSetAsL` silently return the 4-loop value instead of the 5-loop one when called with `nl=5`. 

An upgrade to version 3.1 would fix this, but in principle, changing the two lines above would be enough to ensure a proper evaluation of the functions.

**Comment by DavidMStraub** [comment]
Thanks for the heads-up. I don't think it makes sense patching this as we already have #9 - @mfael86, will you have time to add a unit test so we can merge this?

**Comment by mfael86** [comment]
Hi, this is still in my to-do list!

**Comment by s-kuberski** [comment]
Hi, makes totally sense to directly switch to 3.1. I saw the issue but didn't know if you were pursuing it.

**Comment by DavidMStraub** [comment]
Alright thanks! Closing as covered by #8 then.
