### ISSUE TITLE
Relicense rundec-python under MIT

### ISSUE THREAD

**Issue by JLTastet** [DavidMStraub/rundec-python#2]
The (C)RunDec authors have decided to relicense their code under the MIT license, in order to be more compatible with the rest of the ecosystem (e.g. [Wilson](https://wilson-eft.github.io/), [flav.io](https://flav-io.github.io/)). The updated source is available at https://www.ttp.kit.edu/preprints/2017/ttp17-011.

I think it would now make sense to relicense this Python wrapper as well. What do you think?

**Comment by DavidMStraub** [comment]
Awesome. Yes, I'll do that. Thanks!

**Comment by JLTastet** [comment]
Thanks!
