### ISSUE TITLE
Installation fails on Windows with Python 3.8

### ISSUE THREAD

**Issue by peterstangl** [DavidMStraub/rundec-python#3]
It looks like on PyPI there is no `rundec 0.5.2` wheel for Windows. So on Windows, pip with a Python version up to 3.7 is probably able to install `rundec 0.5.1` instead, for which there is a Windows wheel. But if the Python version is 3.8, pip seems to be unable to install rundec on Windows.

**Comment by DavidMStraub** [comment]
Interesting. Apparently I used AppVeyor in the past to build the Windows Wheels, but nowadays Travis should be able to do it, too. Will give it a try now ...

**Comment by DavidMStraub** [comment]
Looks good! Now someone should test it :hand_over_mouth:

**Comment by serranojust** [comment]
It's working, thanks!
