### ISSUE TITLE
Upgrade to Rundec 3.1

### ISSUE THREAD

**Issue by mfael86** [DavidMStraub/rundec-python#8]
Rundec was updated to version 3.1 (download at https://www.ttp.kit.edu/preprints/2017/ttp17-011) and now it implements the relations between kinetic and MSbar mass from https://arxiv.org/pdf/2011.11655.pdf.

Implement in python the functions `mMS2mKIN` and `mKIN2mMS`.

**Comment by DavidMStraub** [comment]
Fixed by #9.
